### ISSUE TITLE
Can this script encrypt php script??

### ISSUE THREAD

**Issue by Akker13** [arajapandi/php-python-encrypt-decrypt#2]

**Comment by arajapandi** [comment]
This script will encrypt/decrypt given string

**Comment by Akker13** [comment]
Sir can you help me encrypt my script with this tools?? And how the step

**Comment by Akker13** [comment]
Sorry sir can i encrypt this script with your tool
This is my script

**Comment by Akker13** [comment]
Sir can you help me encrypt this script with your tools

**Comment by arajapandi** [comment]
This script is not for file encryption. what is your usecase ?

**Comment by Akker13** [comment]
Any rcomended tool for encrypt script php??

**Comment by arajapandi** [comment]
please check below list, I hope this helps.
    phpBolt (Free)
    Zend Guard
    IonCube
    phpSHIELD

**Comment by Akker13** [comment]
Okay sir i will try this
